#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]

syntect_theme   = "~/.config/yazi/cdmx-jogorman.tmTheme"

border_style    = { fg = "#968878" }
cwd             = { fg = "#0d7892" }
find_keyword    = { bold = true, fg = "#8b681c" }
find_position   = { fg = "#181a17" }
marker_copied   = { bg = "#8b681c", fg = "#f7f0e7" }
marker_cut      = { bg = "#a8321c", fg = "#f7f0e7" }
marker_selected = { bg = "#e0d0bd", fg = "#181a17" }
count_selected  = { bg = "#0d7892", fg = "#f7f0e7" }
count_copied    = { bg = "#8b681c", fg = "#f7f0e7" }
count_cut       = { bg = "#a8321c", fg = "#f7f0e7" }

[cmp]
active   = { bg = "#e0d0bd", fg = "#181a17" }
border   = { fg = "#1a5b8c" }
inactive = { fg = "#2a2b26" }

[tabs]
active   = { bg = "#0d7892", fg = "#f7f0e7" }
inactive = { bg = "#e0d0bd", fg = "#2a2b26" }

[filetype]
rules = [
    { fg = "#0d7892", mime = "image/*" },
    { fg = "#8b681c", mime = "video/*" },
    { fg = "#8b681c", mime = "audio/*" },
    { fg = "#6d4f76", mime = "application/zip" },
    { fg = "#6d4f76", mime = "application/gzip" },
    { fg = "#6d4f76", mime = "application/x-tar" },
    { fg = "#6d4f76", mime = "application/x-bzip" },
    { fg = "#6d4f76", mime = "application/x-bzip2" },
    { fg = "#6d4f76", mime = "application/x-7z-compressed" },
    { fg = "#6d4f76", mime = "application/x-rar" },
    { fg = "#6d4f76", mime = "application/xz" },
    { fg = "#2e6f4a", mime = "application/doc" },
    { fg = "#2e6f4a", mime = "application/pdf" },
    { fg = "#2e6f4a", mime = "application/rtf" },
    { fg = "#2e6f4a", mime = "application/vnd.*" },
    { bold = true, fg = "#0d7892", mime = "inode/directory" },
    { fg = "#2a2b26", mime = "*" }
]

[help]
desc    = { fg = "#2a2b26" }
footer  = { fg = "#8a5636" }
hovered = { bg = "#e0d0bd", fg = "#181a17" }
on      = { fg = "#0d7892" }
run     = { fg = "#0d7892" }

[input]
border   = { fg = "#1a5b8c" }
selected = { bg = "#e0d0bd" }
title    = { fg = "#0d7892" }
value    = { fg = "#2a2b26" }

[pick]
active   = { fg = "#0d7892" }
border   = { fg = "#1a5b8c" }
inactive = { fg = "#2a2b26" }

[mode]
normal_main = { bg = "#0d7892", bold = true, fg = "#f7f0e7" }
select_main = { bg = "#8b681c", bold = true, fg = "#f7f0e7" }
unset_main  = { bg = "#a8321c", bold = true, fg = "#f7f0e7" }

[status]
perm_sep        = { fg = "#6d6259" }
perm_type       = { fg = "#6d4f76" }
perm_read       = { fg = "#8b681c" }
perm_write      = { fg = "#a8321c" }
perm_exec       = { fg = "#2e6f4a" }
progress_error  = { bg = "#efe4d6", fg = "#a8321c" }
progress_label  = { bg = "#efe4d6", fg = "#2a2b26" }
progress_normal = { bg = "#efe4d6", fg = "#0d7892" }

[tasks]
border  = { fg = "#1a5b8c" }
hovered = { bg = "#e0d0bd", fg = "#181a17" }
title   = { fg = "#2a2b26" }

[which]
cand             = { fg = "#0d7892" }
desc             = { fg = "#2a2b26" }
mask             = { bg = "#efe4d6" }
rest             = { fg = "#0d7892" }
separator_style  = { fg = "#6d6259" }
