#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]

syntect_theme   = "~/.config/yazi/miku-stars.tmTheme"

border_style    = { fg = "#3f6699" }
cwd             = { fg = "#6de3e5" }
find_keyword    = { bold = true, fg = "#f7d774" }
find_position   = { fg = "#eef6ff" }
marker_copied   = { bg = "#f7d774", fg = "#0b0d13" }
marker_cut      = { bg = "#ff4f8b", fg = "#0b0d13" }
marker_selected = { bg = "#1e2c47", fg = "#6de3e5" }
count_selected  = { bg = "#6de3e5", fg = "#0b0d13" }
count_copied    = { bg = "#f7d774", fg = "#0b0d13" }
count_cut       = { bg = "#ff4f8b", fg = "#0b0d13" }

[cmp]
active   = { bg = "#1e2c47", fg = "#6de3e5" }
border   = { fg = "#5aa9f0" }
inactive = { fg = "#cfe3f7" }

[tabs]
active   = { bg = "#6de3e5", fg = "#0b0d13" }
inactive = { bg = "#1e2c47", fg = "#cfe3f7" }

[filetype]
rules = [
    { fg = "#6de3e5", mime = "image/*" },
    { fg = "#f7d774", mime = "video/*" },
    { fg = "#f7d774", mime = "audio/*" },
    { fg = "#b18bd8", mime = "application/zip" },
    { fg = "#b18bd8", mime = "application/gzip" },
    { fg = "#b18bd8", mime = "application/x-tar" },
    { fg = "#b18bd8", mime = "application/x-bzip" },
    { fg = "#b18bd8", mime = "application/x-bzip2" },
    { fg = "#b18bd8", mime = "application/x-7z-compressed" },
    { fg = "#b18bd8", mime = "application/x-rar" },
    { fg = "#b18bd8", mime = "application/xz" },
    { fg = "#6fd6a8", mime = "application/doc" },
    { fg = "#6fd6a8", mime = "application/pdf" },
    { fg = "#6fd6a8", mime = "application/rtf" },
    { fg = "#6fd6a8", mime = "application/vnd.*" },
    { bold = true, fg = "#6de3e5", mime = "inode/directory" },
    { fg = "#cfe3f7", mime = "*" }
]

[help]
desc    = { fg = "#cfe3f7" }
footer  = { fg = "#9a8fa8" }
hovered = { bg = "#1e2c47", fg = "#6de3e5" }
on      = { fg = "#6de3e5" }
run     = { fg = "#6de3e5" }

[input]
border   = { fg = "#5aa9f0" }
selected = { bg = "#1e2c47" }
title    = { fg = "#6de3e5" }
value    = { fg = "#cfe3f7" }

[pick]
active   = { fg = "#6de3e5" }
border   = { fg = "#5aa9f0" }
inactive = { fg = "#cfe3f7" }

[mode]
normal_main = { bg = "#6de3e5", bold = true, fg = "#0b0d13" }
select_main = { bg = "#f7d774", bold = true, fg = "#0b0d13" }
unset_main  = { bg = "#ff4f8b", bold = true, fg = "#0b0d13" }

[status]
perm_sep        = { fg = "#507bb0" }
perm_type       = { fg = "#b18bd8" }
perm_read       = { fg = "#f7d774" }
perm_write      = { fg = "#ff4f8b" }
perm_exec       = { fg = "#6fd6a8" }
progress_error  = { bg = "#141b2b", fg = "#ff4f8b" }
progress_label  = { bg = "#141b2b", fg = "#cfe3f7" }
progress_normal = { bg = "#141b2b", fg = "#6de3e5" }

[tasks]
border  = { fg = "#5aa9f0" }
hovered = { bg = "#1e2c47", fg = "#6de3e5" }
title   = { fg = "#cfe3f7" }

[which]
cand             = { fg = "#6de3e5" }
desc             = { fg = "#cfe3f7" }
mask             = { bg = "#141b2b" }
rest             = { fg = "#6de3e5" }
separator_style  = { fg = "#507bb0" }
