background            #000000
foreground            #edbac3
cursor                #e070c0
cursor_text_color     #000000
selection_background  #36192a
selection_foreground  #edbac3
color0                #1a0c14
color8                #a85e74
color1                #e82050
color9                #e82050
color2                #b05c82
color10               #b05c82
color3                #f0d090
color11               #f0d090
color4                #a060d8
color12               #a060d8
color5                #e070c0
color13               #e070c0
color6                #f49ab0
color14               #f49ab0
color7                #c87888
color15               #faeaec
active_border_color   #e070c0
inactive_border_color #36192a
bell_border_color     #f0d090
active_tab_foreground #000000
active_tab_background #e070c0
inactive_tab_foreground #c87888
inactive_tab_background #1a0c14
